# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.7753e+28, 3.0579e+32, 1.8469e+25],
        [1.6458e+19, 5.5808e-11, 2.8175e+20],
        [1.0834e+24, 1.3844e-14, 1.8888e+31],
        [1.1839e+22, 3.2039e-12, 1.7743e+28],
        [2.0535e-19, 4.5080e+21, 1.8389e+25]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3463, 0.6099, 0.5247],
        [0.2754, 0.6356, 0.5688],
        [0.3183, 0.4220, 0.6031],
        [0.7786, 0.8622, 0.7890],
        [0.4022, 0.2133, 0.3757]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [7]:
x[1:3] = 2
print(x)

tensor([[0.3463, 0.6099, 0.5247],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.4022, 0.2133, 0.3757]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [32]:
from torch import tensor, Tensor
x1 = Tensor(2,17)
x2 = torch.FloatTensor(3,1)
x3 = torch.LongTensor(5,2,1)
x3[:] = 7
#x4 = torch.ByteTensor(5,)
x5 = torch.zeros((5,), dtype=torch.bool)
x5[1:x5.size()[0]-1] = True
print(x1,x2,x3,x5)

tensor([[0.0000e+00, 0.0000e+00, 9.9492e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 7.7052e+31, 1.9447e+31,
         5.0207e+28, 2.3329e-18, 4.2330e+21, 7.2251e+28, 7.0368e+28],
        [3.3127e-18, 2.5182e-12, 7.1856e+22, 1.8609e+34, 1.8179e+31, 1.8524e+28,
         9.6647e+35, 2.0076e+29, 7.3185e+28, 6.1948e-04, 1.1513e-38, 0.0000e+00,
         0.0000e+00, 2.7045e-43, 0.0000e+00, 1.3917e-37, 0.0000e+00]]) tensor([[0.0000e+00],
        [0.0000e+00],
        [6.8664e-44]]) tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]]) tensor([False,  True,  True,  True, False])


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [33]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.6888, 1.2684, 1.4124],
        [2.3403, 2.2443, 2.8827],
        [2.7828, 2.8888, 2.6426],
        [2.0036, 2.3057, 2.5757],
        [0.7707, 1.0641, 1.0725]])


### 2.2 Addition: syntax 2

In [34]:
print(torch.add(x, y))

tensor([[0.6888, 1.2684, 1.4124],
        [2.3403, 2.2443, 2.8827],
        [2.7828, 2.8888, 2.6426],
        [2.0036, 2.3057, 2.5757],
        [0.7707, 1.0641, 1.0725]])


### 2.3 Addition: giving an output tensor

In [35]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6888, 1.2684, 1.4124],
        [2.3403, 2.2443, 2.8827],
        [2.7828, 2.8888, 2.6426],
        [2.0036, 2.3057, 2.5757],
        [0.7707, 1.0641, 1.0725]])


### 2.4 Addition: in-place

adds `x`to `y`

In [36]:
y.add_(x)
print(y)

tensor([[0.6888, 1.2684, 1.4124],
        [2.3403, 2.2443, 2.8827],
        [2.7828, 2.8888, 2.6426],
        [2.0036, 2.3057, 2.5757],
        [0.7707, 1.0641, 1.0725]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [37]:
print(x[:, 1])

tensor([0.6099, 2.0000, 2.0000, 2.0000, 0.2133])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [63]:
a = torch.randn(1,5)
b = torch.randn(1,5)
c = a *b;
print(c == a.mul_(b))
print(a/b)
a = torch.randn(2,4)
b = torch.randn(4,2)
print(torch.matmul(a,b).size())

tensor([[True, True, True, True, True]])
tensor([[-2.8363,  0.8788, -1.9281, -0.6544,  1.8667]])
torch.Size([2, 2])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [64]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [65]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [66]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [8]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [75]:
a = torch.ones(5,2)
print(a)
a = a.numpy()
print(a)
a = torch.from_numpy(a)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [76]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
